yml

name: "auto-anchor-scroll-app CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build:prod

      - name: Eslint and Prettierrc
        run: npm run lint

      - name: Run tests
        run: npm test
